ResourcesPath: ../rosenpin.io/resources
Username: alexcrichton
AuthCode: AUTHCODE
HTTPRequestTimeout: 10s
MaxProjects: 12
IncludeForks: true
SortMode: stars
GitPlatform: github
ProfileURL: http://www.github.com/alexcrichton
ReloadInterval: 24h
